/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.java_active_record.test_project.database_1.models;

import java.io.IOException;
import java.util.Set;

import com.rapleaf.java_active_record.test_project.database_1.IDatabase1;

import com.rapleaf.java_active_record.ModelWithId;
import com.rapleaf.java_active_record.BelongsToAssociation;
import com.rapleaf.java_active_record.HasManyAssociation;
import com.rapleaf.java_active_record.HasOneAssociation;

import com.rapleaf.java_active_record.test_project.IDatabases;

public class Comment extends ModelWithId {
  // Fields
  private String __content;
  private Integer __commenter_id;
  private Integer __commented_on_id;

  // Associations
  private final BelongsToAssociation<User> __assoc_user;
  private final BelongsToAssociation<Post> __assoc_post;

  public Comment(int id, final String content, final Integer commenter_id, final Integer commented_on_id, IDatabases databases) {
    super(id);
    this.__content = content;
    this.__commenter_id = commenter_id;
    this.__commented_on_id = commented_on_id;
    this.__assoc_user = new BelongsToAssociation<User>(databases.getDatabase1().users(), commenter_id);
    this.__assoc_post = new BelongsToAssociation<Post>(databases.getDatabase1().posts(), commented_on_id);
  }

  public String getContent(){
    return __content;
  }

  public void setContent(String newval){
    this.__content = newval;
  }

  public Integer getCommenterId(){
    return __commenter_id;
  }

  public void setCommenterId(Integer newval){
    this.__commenter_id = newval;
  }

  public Integer getCommentedOnId(){
    return __commented_on_id;
  }

  public void setCommentedOnId(Integer newval){
    this.__commented_on_id = newval;
  }
  
  public User getUser() throws IOException {
    return __assoc_user.get();
  }
  
  public Post getPost() throws IOException {
    return __assoc_post.get();
  }
}
