/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.java_active_record.test_project.database_1.models;

import java.io.IOException;
import java.util.Set;

import com.rapleaf.java_active_record.test_project.database_1.IDatabase1;

import com.rapleaf.java_active_record.ModelWithId;
import com.rapleaf.java_active_record.BelongsToAssociation;
import com.rapleaf.java_active_record.HasManyAssociation;
import com.rapleaf.java_active_record.HasOneAssociation;

import com.rapleaf.java_active_record.test_project.IDatabases;

public class Follower extends ModelWithId {
  // Fields
  private Integer __follower_id;
  private Integer __followed_id;

  // Associations
  private final BelongsToAssociation<Follower, Integer> __assoc_follower;
  private final BelongsToAssociation<Follower, Integer> __assoc_followed;

  public Follower(long id, final Integer follower_id, final Integer followed_id, IDatabases databases) {
    super(id);
    this.__follower_id = follower_id;
    this.__followed_id = followed_id;
    this.__assoc_follower = new BelongsToAssociation<Follower, Integer>(databases.getDatabase1().followers(), follower_id);
    this.__assoc_followed = new BelongsToAssociation<Follower, Integer>(databases.getDatabase1().followers(), followed_id);
  }

  public Integer getFollowerId(){
    return __follower_id;
  }

  public void setFollowerId(Integer newval){
    this.__follower_id = newval;
  }

  public Integer getFollowedId(){
    return __followed_id;
  }

  public void setFollowedId(Integer newval){
    this.__followed_id = newval;
  }
  
  public Follower getFollower() throws IOException {
    return __assoc_follower.get();
  }
  
  public Follower getFollowed() throws IOException {
    return __assoc_followed.get();
  }
}

