/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20110324000133 */
package com.rapleaf.java_active_record.test_project.database_1.models;

import java.io.IOException;
import java.util.Set;

import com.rapleaf.java_active_record.test_project.database_1.IDatabase1;

import com.rapleaf.java_active_record.ModelWithId;
import com.rapleaf.java_active_record.BelongsToAssociation;
import com.rapleaf.java_active_record.HasManyAssociation;
import com.rapleaf.java_active_record.HasOneAssociation;

import com.rapleaf.java_active_record.test_project.IDatabases;

public class Image extends ModelWithId {
  // Fields
  private Integer __user_id;

  // Associations
  private final BelongsToAssociation<User> __assoc_user;

  public Image(int id, final Integer user_id, IDatabases databases) {
    super(id);
    this.__user_id = user_id;
    this.__assoc_user = new BelongsToAssociation<User>(databases.getDatabase1().users(), user_id);
  }

  public Integer getUserId(){
    return __user_id;
  }

  public void setUserId(Integer newval){
    this.__user_id = newval;
  }
  
  public User getUser() throws IOException {
    return __assoc_user.get();
  }
}
