/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.java_active_record.test_project.database_1.models;

import java.io.IOException;
import java.util.Set;

import com.rapleaf.java_active_record.test_project.database_1.IDatabase1;

import com.rapleaf.java_active_record.ModelWithId;
import com.rapleaf.java_active_record.BelongsToAssociation;
import com.rapleaf.java_active_record.HasManyAssociation;
import com.rapleaf.java_active_record.HasOneAssociation;

import com.rapleaf.java_active_record.test_project.IDatabases;

public class Post extends ModelWithId {
  // Fields
  private String __title;
  private Long __posted_at_millis;
  private Integer __user_id;

  // Associations
  private final BelongsToAssociation<User> __assoc_user;
  private final HasManyAssociation<Comment> __assoc_comments;

  public Post(int id, final String title, final Long posted_at_millis, final Integer user_id, IDatabases databases) {
    super(id);
    this.__title = title;
    this.__posted_at_millis = posted_at_millis;
    this.__user_id = user_id;
    this.__assoc_user = new BelongsToAssociation<User>(databases.getDatabase1().users(), user_id);
    this.__assoc_comments = new HasManyAssociation<Comment>(databases.getDatabase1().comments(), "commented_on_id", id);
  }

  public String getTitle(){
    return __title;
  }

  public void setTitle(String newval){
    this.__title = newval;
  }

  public Long getPostedAtMillis(){
    return __posted_at_millis;
  }

  public void setPostedAtMillis(Long newval){
    this.__posted_at_millis = newval;
  }

  public Integer getUserId(){
    return __user_id;
  }

  public void setUserId(Integer newval){
    this.__user_id = newval;
  }
  
  public User getUser() throws IOException {
    return __assoc_user.get();
  }
  
  public Set<Comment> getComments() throws IOException {
    return __assoc_comments.get();
  }
}
