
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.iface;

import com.rapleaf.jack.test_project.database_1.models.Image;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IImagePersistence extends IModelPersistence<Image> {
  public Image create(final Integer user_id) throws IOException;
  public Image create() throws IOException;

  public Image createDefaultInstance() throws IOException;
  public Set<Image> findByUserId(Integer value)  throws IOException;
}
