
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20110324000133 */
package com.rapleaf.jack.test_project.database_1.iface;

import com.rapleaf.jack.test_project.database_1.models.Post;
import java.io.IOException;
import java.util.Map;
import java.util.Set;

import com.rapleaf.jack.IModelPersistence;

public interface IPostPersistence extends IModelPersistence<Post> {
  public Post create(final String title, final Long posted_at_millis, final Integer user_id) throws IOException;
  public Set<Post> findByTitle(String value)  throws IOException;
  public Set<Post> findByPostedAtMillis(Long value)  throws IOException;
  public Set<Post> findByUserId(Integer value)  throws IOException;
}
