
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.impl;

import java.io.IOException;

import com.rapleaf.jack.test_project.database_1.IDatabase1;
import com.rapleaf.jack.queries.GenericQuery;
import com.rapleaf.jack.BaseDatabaseConnection;
import com.rapleaf.jack.test_project.database_1.iface.ICommentPersistence;
import com.rapleaf.jack.test_project.database_1.iface.IImagePersistence;
import com.rapleaf.jack.test_project.database_1.iface.IPostPersistence;
import com.rapleaf.jack.test_project.database_1.iface.IUserPersistence;

import com.rapleaf.jack.test_project.IDatabases;

public class Database1Impl implements IDatabase1 {
  
  private final BaseDatabaseConnection conn;
  private final IDatabases databases;
  private ICommentPersistence comments;
  private IImagePersistence images;
  private IPostPersistence posts;
  private IUserPersistence users;

  public Database1Impl(BaseDatabaseConnection conn, IDatabases databases) {
    this.conn = conn;
    this.databases = databases;
  }

  public GenericQuery.Builder createQuery() {
    return GenericQuery.create(conn);
  }

  public ICommentPersistence comments(){
    if (comments == null) {
      comments = new BaseCommentPersistenceImpl(conn, databases);
    }
    return comments;
  }

  public IImagePersistence images(){
    if (images == null) {
      images = new BaseImagePersistenceImpl(conn, databases);
    }
    return images;
  }

  public IPostPersistence posts(){
    if (posts == null) {
      posts = new BasePostPersistenceImpl(conn, databases);
    }
    return posts;
  }

  public IUserPersistence users(){
    if (users == null) {
      users = new BaseUserPersistenceImpl(conn, databases);
    }
    return users;
  }

  public boolean deleteAll() throws IOException {
    boolean success = true;
    try {
    success &= comments().deleteAll();
    success &= images().deleteAll();
    success &= posts().deleteAll();
    success &= users().deleteAll();
    } catch (IOException e) {
      throw e;
    }
    return success;
  }

  public void disableCaching() {
    comments().disableCaching();
    images().disableCaching();
    posts().disableCaching();
    users().disableCaching();
  }

  public void setAutoCommit(boolean autoCommit) {
    conn.setAutoCommit(autoCommit);
  }

  public boolean getAutoCommit() {
    return conn.getAutoCommit();
  }

  public void commit() {
    conn.commit();
  }

  public void rollback() {
    conn.rollback();
  }

  public void resetConnection() {
    conn.resetConnection();
  }

  public IDatabases getDatabases() {
    return databases;
  }

}
