
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project;
import com.rapleaf.jack.test_project.database_1.IDatabase1;

import java.io.Serializable;

public interface IDatabases extends Serializable {
  public IDatabase1 getDatabase1();
}
