
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project;
import com.rapleaf.jack.test_project.database_1.IDatabase1;
import com.rapleaf.jack.test_project.database_1.mock_impl.MockDatabase1Impl;

public class MockDatabasesImpl implements IDatabases {
  private final IDatabase1 database1;

  public MockDatabasesImpl() {
    this.database1 = new MockDatabase1Impl(this);
  }

  public IDatabase1 getDatabase1() {
    return database1;
  }
  
}

