
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project;

import com.rapleaf.jack.GenericDatabases;
import com.rapleaf.jack.test_project.database_1.IDatabase1;
import com.rapleaf.jack.test_project.database_1.transaction.Database1TransactionGroup;

public interface IDatabases extends GenericDatabases {
  IDatabase1 getDatabase1();
  Database1TransactionGroup getDatabase1TransactionGroup();
}
