
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project;

import com.rapleaf.jack.GenericDatabases;
import com.rapleaf.jack.test_project.database_1.IDatabase1;
import com.rapleaf.jack.runner.SqlRunner;

public interface IDatabases extends GenericDatabases {
  IDatabase1 getDatabase1();
  SqlRunner.Builder<IDatabase1> getDatabase1SqlRunner();
}
