
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.iface;

import com.rapleaf.jack.test_project.database_1.models.Comment;
import com.rapleaf.jack.test_project.database_1.query.CommentQueryBuilder;
import com.rapleaf.jack.test_project.database_1.query.CommentDeleteBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.List;

import com.rapleaf.jack.IModelPersistence;

public interface ICommentPersistence extends IModelPersistence<Comment> {
  Comment create(final String content, final int commenter_id, final long commented_on_id, final long created_at) throws IOException;
  Comment create(final int commenter_id, final long commented_on_id, final long created_at) throws IOException;

  Comment createDefaultInstance() throws IOException;
  List<Comment> findByContent(String value)  throws IOException;
  List<Comment> findByCommenterId(int value)  throws IOException;
  List<Comment> findByCommentedOnId(long value)  throws IOException;
  List<Comment> findByCreatedAt(long value)  throws IOException;

  CommentQueryBuilder query();

  CommentDeleteBuilder delete();
}
