
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.iface;

import com.rapleaf.jack.test_project.database_1.models.User;
import com.rapleaf.jack.test_project.database_1.query.UserQueryBuilder;
import com.rapleaf.jack.test_project.database_1.query.UserDeleteBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.List;

import com.rapleaf.jack.IModelPersistence;

public interface IUserPersistence extends IModelPersistence<User> {
  public User create(final String handle, final Long created_at_millis, final int num_posts, final Long some_date, final Long some_datetime, final String bio, final String _tbl, final byte[] some_binary, final Double some_float, final Double some_decimal, final Boolean some_boolean) throws IOException;
  public User create(final String handle, final int num_posts) throws IOException;

  public User createDefaultInstance() throws IOException;
  public List<User> findByHandle(String value)  throws IOException;
  public List<User> findByCreatedAtMillis(Long value)  throws IOException;
  public List<User> findByNumPosts(int value)  throws IOException;
  public List<User> findBySomeDate(Long value)  throws IOException;
  public List<User> findBySomeDatetime(Long value)  throws IOException;
  public List<User> findByBio(String value)  throws IOException;
  public List<User> findBy_tbl(String value)  throws IOException;
  public List<User> findBySomeBinary(byte[] value)  throws IOException;
  public List<User> findBySomeFloat(Double value)  throws IOException;
  public List<User> findBySomeDecimal(Double value)  throws IOException;
  public List<User> findBySomeBoolean(Boolean value)  throws IOException;

  public UserQueryBuilder query();

  public UserDeleteBuilder delete();
}
