
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.iface;

import com.rapleaf.jack.test_project.database_1.models.TestStore;
import com.rapleaf.jack.test_project.database_1.query.TestStoreQueryBuilder;
import com.rapleaf.jack.test_project.database_1.query.TestStoreDeleteBuilder;

import java.io.IOException;
import java.util.Map;
import java.util.List;

import com.rapleaf.jack.IModelPersistence;

public interface ITestStorePersistence extends IModelPersistence<TestStore> {
  TestStore create(final Integer entry_type, final Long entry_scope, final String entry_key, final String entry_value, final Long created_at, final Long updated_at) throws IOException;
  TestStore create() throws IOException;

  TestStore createDefaultInstance() throws IOException;
  List<TestStore> findByEntryType(Integer value)  throws IOException;
  List<TestStore> findByEntryScope(Long value)  throws IOException;
  List<TestStore> findByEntryKey(String value)  throws IOException;
  List<TestStore> findByEntryValue(String value)  throws IOException;
  List<TestStore> findByCreatedAt(Long value)  throws IOException;
  List<TestStore> findByUpdatedAt(Long value)  throws IOException;

  TestStoreQueryBuilder query();

  TestStoreDeleteBuilder delete();
}
