
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.models;

import com.rapleaf.jack.ModelIdWrapper;

public class CommentId implements ModelIdWrapper<CommentId>{
  private final long id;

  public CommentId(Long id){
    this.id = id;
  }

  @Override
  public Long getId(){
    return Long.valueOf(this.id);
  }

  @Override
  public int compareTo(CommentId other){
    return this.getId().compareTo(other.getId());
  }

  @Override
  public boolean equals(Object other){
    if(other instanceof CommentId){
      return this.getId().equals(((CommentId) other).getId());
    }
    return false;
  }

  @Override
  public int hashCode(){
    return this.getId().hashCode();
  }
}
