
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20110324000133 */
package com.rapleaf.jack.test_project.database_1.models;

import java.io.IOException;
import java.util.Set;

import com.rapleaf.jack.test_project.database_1.IDatabase1;

import com.rapleaf.jack.ModelWithId;
import com.rapleaf.jack.BelongsToAssociation;
import com.rapleaf.jack.HasManyAssociation;
import com.rapleaf.jack.HasOneAssociation;

import com.rapleaf.jack.test_project.IDatabases;

public class User extends ModelWithId {
  // Fields
  private String __handle;
  private Long __created_at_millis;
  private int __num_posts;
  private Long __some_date;
  private Long __some_datetime;
  private String __bio;
  private byte[] __some_binary;
  private Double __some_float;
  private Boolean __some_boolean;

  // Associations
  private final HasManyAssociation<Post> __assoc_posts;
  private final HasManyAssociation<Comment> __assoc_comments;
  private final HasOneAssociation<Image> __assoc_image;

  public User(int id, final String handle, final Long created_at_millis, final int num_posts, final Long some_date, final Long some_datetime, final String bio, final byte[] some_binary, final Double some_float, final Boolean some_boolean, IDatabases databases) {
    super(id);
    this.__handle = handle;
    this.__created_at_millis = created_at_millis;
    this.__num_posts = num_posts;
    this.__some_date = some_date;
    this.__some_datetime = some_datetime;
    this.__bio = bio;
    this.__some_binary = some_binary;
    this.__some_float = some_float;
    this.__some_boolean = some_boolean;
    this.__assoc_posts = new HasManyAssociation<Post>(databases.getDatabase1().posts(), "user_id", id);
    this.__assoc_comments = new HasManyAssociation<Comment>(databases.getDatabase1().comments(), "commenter_id", id);
    this.__assoc_image = new HasOneAssociation<Image>(databases.getDatabase1().images(), "image_id", id);
  }

  public String getHandle(){
    return __handle;
  }

  public void setHandle(String newval){
    this.__handle = newval;
  }

  public Long getCreatedAtMillis(){
    return __created_at_millis;
  }

  public void setCreatedAtMillis(Long newval){
    this.__created_at_millis = newval;
  }

  public int getNumPosts(){
    return __num_posts;
  }

  public void setNumPosts(int newval){
    this.__num_posts = newval;
  }

  public Long getSomeDate(){
    return __some_date;
  }

  public void setSomeDate(Long newval){
    this.__some_date = newval;
  }

  public Long getSomeDatetime(){
    return __some_datetime;
  }

  public void setSomeDatetime(Long newval){
    this.__some_datetime = newval;
  }

  public String getBio(){
    return __bio;
  }

  public void setBio(String newval){
    this.__bio = newval;
  }

  public byte[] getSomeBinary(){
    return __some_binary;
  }

  public void setSomeBinary(byte[] newval){
    this.__some_binary = newval;
  }

  public Double getSomeFloat(){
    return __some_float;
  }

  public void setSomeFloat(Double newval){
    this.__some_float = newval;
  }

  public Boolean isSomeBoolean(){
    return __some_boolean;
  }

  public void setSomeBoolean(Boolean newval){
    this.__some_boolean = newval;
  }

  public Set<Post> getPosts() throws IOException {
    return __assoc_posts.get();
  }

  public Set<Comment> getComments() throws IOException {
    return __assoc_comments.get();
  }

  public Image getImage() throws IOException {
    return __assoc_image.get();
  }

  public String toString() {
    return "<User"
      + " handle: " + __handle
      + " created_at_millis: " + __created_at_millis
      + " num_posts: " + __num_posts
      + " some_date: " + __some_date
      + " some_datetime: " + __some_datetime
      + " bio: " + __bio
      + " some_binary: " + __some_binary
      + " some_float: " + __some_float
      + " some_boolean: " + __some_boolean
      + ">";
  }
}
