/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20110324000133 */
package com.rapleaf.java_active_record.test_project.database_1.iface;

import com.rapleaf.java_active_record.test_project.database_1.models.Comment;
import java.io.IOException;

import com.rapleaf.java_active_record.IModelPersistence;

public interface ICommentPersistence extends IModelPersistence<Comment> {
  public Comment create(final String content, final Integer commenter_id, final Integer commented_on_id) throws IOException;
}
