/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.java_active_record.test_project.database_1.iface;

import com.rapleaf.java_active_record.test_project.database_1.models.Image;
import java.io.IOException;

import com.rapleaf.java_active_record.IModelPersistence;

public interface IImagePersistence extends IModelPersistence<Image> {
  public Image create(final Integer user_id) throws IOException;
}
