/**
 * Autogenerated
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
/* generated from migration version 20110324000133 */
package com.rapleaf.java_active_record.test_project.database_1.iface;

import com.rapleaf.java_active_record.test_project.database_1.models.User;
import java.io.IOException;

import com.rapleaf.java_active_record.IModelPersistence;

public interface IUserPersistence extends IModelPersistence<User> {
  public User create(final String handle, final Long created_at_millis, final Integer num_posts, final Long some_date, final Long some_datetime, final String bio, final byte[] some_binary, final Double some_float, final Boolean some_boolean) throws IOException;
}
