/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1.query;

import java.util.Set;

import com.rapleaf.jack.queries.AbstractDeleteBuilder;
import com.rapleaf.jack.queries.where_operators.IWhereOperator;
import com.rapleaf.jack.queries.where_operators.JackMatchers;
import com.rapleaf.jack.queries.WhereConstraint;
import com.rapleaf.jack.test_project.database_1.iface.ITestStorePersistence;
import com.rapleaf.jack.test_project.database_1.models.TestStore;


public class TestStoreDeleteBuilder extends AbstractDeleteBuilder<TestStore> {

  public TestStoreDeleteBuilder(ITestStorePersistence caller) {
    super(caller);
  }

  public TestStoreDeleteBuilder id(Long value) {
    addId(value);
    return this;
  }

  public TestStoreDeleteBuilder idIn(Set<Long> values) {
    addIds(values);
    return this;
  }

  public TestStoreDeleteBuilder scope(String value) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.scope, JackMatchers.equalTo(value)));
    return this;
  }

  public TestStoreDeleteBuilder whereScope(IWhereOperator<String> operator) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.scope, operator));
    return this;
  }

  public TestStoreDeleteBuilder key(String value) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.key, JackMatchers.equalTo(value)));
    return this;
  }

  public TestStoreDeleteBuilder whereKey(IWhereOperator<String> operator) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.key, operator));
    return this;
  }

  public TestStoreDeleteBuilder type(String value) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.type, JackMatchers.equalTo(value)));
    return this;
  }

  public TestStoreDeleteBuilder whereType(IWhereOperator<String> operator) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.type, operator));
    return this;
  }

  public TestStoreDeleteBuilder value(String value) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.value, JackMatchers.equalTo(value)));
    return this;
  }

  public TestStoreDeleteBuilder whereValue(IWhereOperator<String> operator) {
    addWhereConstraint(new WhereConstraint<String>(TestStore._Fields.value, operator));
    return this;
  }

  public TestStoreDeleteBuilder createdAt(Long value) {
    addWhereConstraint(new WhereConstraint<Long>(TestStore._Fields.created_at, JackMatchers.equalTo(value)));
    return this;
  }

  public TestStoreDeleteBuilder whereCreatedAt(IWhereOperator<Long> operator) {
    addWhereConstraint(new WhereConstraint<Long>(TestStore._Fields.created_at, operator));
    return this;
  }

  public TestStoreDeleteBuilder updatedAt(Long value) {
    addWhereConstraint(new WhereConstraint<Long>(TestStore._Fields.updated_at, JackMatchers.equalTo(value)));
    return this;
  }

  public TestStoreDeleteBuilder whereUpdatedAt(IWhereOperator<Long> operator) {
    addWhereConstraint(new WhereConstraint<Long>(TestStore._Fields.updated_at, operator));
    return this;
  }
}
