
/**
 * Autogenerated by Jack
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package com.rapleaf.jack.test_project.database_1;

import java.io.IOException;
import java.sql.SQLException;

import com.rapleaf.jack.DbFixtures;
import com.rapleaf.jack.test_project.DatabasesImpl;
import com.rapleaf.jack.test_project.IDatabases;

public class BaseDatabase1Fixtures extends DbFixtures {

  public static void setup() throws SQLException, IOException {
    setup(new DatabasesImpl());
  }

  public static void setup(IDatabases databases) throws SQLException, IOException {
    databases.getDatabase1().comments().deleteAll();
    databases.getDatabase1().images().deleteAll();
    databases.getDatabase1().lockableModels().deleteAll();
    databases.getDatabase1().posts().deleteAll();
    databases.getDatabase1().testStore().deleteAll();
    databases.getDatabase1().users().deleteAll();
  }
}
